In [90]:
import numpy as np

In [91]:
import pandas as pd

In [4]:
labels = ['a', 'b', 'c']
my_data = [10, 20, 30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [5]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan']) ##O primeiro seria o index e o segundo os valores

In [8]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [9]:
ser1['USA']

np.int64(1)

In [10]:
ser2 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])## Se existir uma correspondencia entre os index ele somará se não, null

In [11]:
ser2+ser1

USA        2
Germany    4
USSR       6
Japan      8
dtype: int64

In [12]:
##DataFrames

In [13]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [14]:
df

          W         X         Y         Z
A  0.906332 -0.925177 -0.488161 -0.336370
B  0.122513  0.512555  1.710561  1.385583
C  0.581661 -1.510301  0.045762 -0.852098
D -1.315880  0.385897 -1.097483  1.987149
E  1.180632 -0.692357 -0.530553 -0.482416

In [15]:
df['W'] ##Vai pegar a coluna de w

A    0.906332
B    0.122513
C    0.581661
D   -1.315880
E    1.180632
Name: W, dtype: float64

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.W ##Mesma coisa que df['W']

A    0.906332
B    0.122513
C    0.581661
D   -1.315880
E    1.180632
Name: W, dtype: float64

In [18]:
df['new'] = df['W'] + df['Y'] ## Criacao de uma nova coluna com o somatório das duas anteriores

In [19]:
df

          W         X         Y         Z       new
A  0.906332 -0.925177 -0.488161 -0.336370  0.418171
B  0.122513  0.512555  1.710561  1.385583  1.833074
C  0.581661 -1.510301  0.045762 -0.852098  0.627423
D -1.315880  0.385897 -1.097483  1.987149 -2.413364
E  1.180632 -0.692357 -0.530553 -0.482416  0.650079

In [20]:
df.drop('new',axis=1, inplace=True)## apagar a coluna da tabela, nesse caso precisamos passar o axis = 1 e o nome,e o inplace é a confirmacao que devemos apagar

In [21]:
df[['Z','X']]

          Z         X
A -0.336370 -0.925177
B  1.385583  0.512555
C -0.852098 -1.510301
D  1.987149  0.385897
E -0.482416 -0.692357

In [22]:
df.loc['C'] ## Pegar a linha A como referência

W    0.581661
X   -1.510301
Y    0.045762
Z   -0.852098
Name: C, dtype: float64

In [23]:
df.iloc[2] ##iloc passa o indice da linha

W    0.581661
X   -1.510301
Y    0.045762
Z   -0.852098
Name: C, dtype: float64

In [24]:
df.loc['B','Y'] ## O primeiro parâmetro indica a linha e a segunda a coluna

np.float64(1.7105606799625634)

In [25]:
df.loc[['A', 'B'], ['W', 'Y']]

          W         Y
A  0.906332 -0.488161
B  0.122513  1.710561

In [26]:
booldf = df>0

In [27]:
booldf

       W      X      Y      Z
A   True  False  False  False
B   True   True   True   True
C   True  False   True  False
D  False   True  False   True
E   True  False  False  False

In [28]:
df[booldf]

          W         X         Y         Z
A  0.906332       NaN       NaN       NaN
B  0.122513  0.512555  1.710561  1.385583
C  0.581661       NaN  0.045762       NaN
D       NaN  0.385897       NaN  1.987149
E  1.180632       NaN       NaN       NaN

In [29]:
df['W'] > 0

A     True
B     True
C     True
D    False
E     True
Name: W, dtype: bool

In [30]:
resultdf = df[df['W']>0]["W"] ##Retornará os valores e não o boolean

In [31]:
resultdf

A    0.906332
B    0.122513
C    0.581661
E    1.180632
Name: W, dtype: float64

In [32]:
boolser = df["W"]>0 ## Pandas compara cada valor na coluna w com 0
result = df[boolser] ## Usamos essa máscara para filtrar as linhas, e retornar valores
mycols = ['Y','X']##
result[mycols]

          Y         X
A -0.488161 -0.925177
B  1.710561  0.512555
C  0.045762 -1.510301
E -0.530553 -0.692357

In [33]:
df

          W         X         Y         Z
A  0.906332 -0.925177 -0.488161 -0.336370
B  0.122513  0.512555  1.710561  1.385583
C  0.581661 -1.510301  0.045762 -0.852098
D -1.315880  0.385897 -1.097483  1.987149
E  1.180632 -0.692357 -0.530553 -0.482416

In [34]:
df[(df['W']> 0) | (df['Y']> 1)]

          W         X         Y         Z
A  0.906332 -0.925177 -0.488161 -0.336370
B  0.122513  0.512555  1.710561  1.385583
C  0.581661 -1.510301  0.045762 -0.852098
E  1.180632 -0.692357 -0.530553 -0.482416

In [35]:
df

          W         X         Y         Z
A  0.906332 -0.925177 -0.488161 -0.336370
B  0.122513  0.512555  1.710561  1.385583
C  0.581661 -1.510301  0.045762 -0.852098
D -1.315880  0.385897 -1.097483  1.987149
E  1.180632 -0.692357 -0.530553 -0.482416

In [36]:
newind = 'CA NY WY OR CO'.split() ## Criacao de um novo index

In [37]:
df['States'] = newind

In [38]:
df

          W         X         Y         Z States
A  0.906332 -0.925177 -0.488161 -0.336370     CA
B  0.122513  0.512555  1.710561  1.385583     NY
C  0.581661 -1.510301  0.045762 -0.852098     WY
D -1.315880  0.385897 -1.097483  1.987149     OR
E  1.180632 -0.692357 -0.530553 -0.482416     CO

In [39]:
df.set_index('States') ## Criacao de estados no index

               W         X         Y         Z
States
CA      0.906332 -0.925177 -0.488161 -0.336370
NY      0.122513  0.512555  1.710561  1.385583
WY      0.581661 -1.510301  0.045762 -0.852098
OR     -1.315880  0.385897 -1.097483  1.987149
CO      1.180632 -0.692357 -0.530553 -0.482416

In [40]:
outside = [ 'G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [41]:
df = pd.DataFrame(np.random.randn(6,2),hier_index,['A', 'B'])

In [42]:
df

             A         B
G1 1  1.630399  0.465039
   2 -0.931855 -0.431517
   3 -1.345218  0.404451
G2 1 -1.549342  0.209616
   2 -0.587965 -0.128538
   3  1.388471  1.439814

In [43]:
df.index.names = ['Groups','Num']

In [44]:
df

                   A         B
Groups Num
G1     1    1.630399  0.465039
       2   -0.931855 -0.431517
       3   -1.345218  0.404451
G2     1   -1.549342  0.209616
       2   -0.587965 -0.128538
       3    1.388471  1.439814

In [45]:
df.loc['G2'].loc[2]

A   -0.587965
B   -0.128538
Name: 2, dtype: float64

In [46]:
df.loc['G1'].loc[1]['B']

np.float64(0.46503922210466736)

In [47]:
df.xs(1, level="Num")

               A         B
Groups
G1      1.630399  0.465039
G2     -1.549342  0.209616

In [48]:
d = {'A': [1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [49]:
df = pd.DataFrame(d)

In [50]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [51]:
df.dropna() ## Vai dropar todos os valores com NAN

     A    B  C
0  1.0  5.0  1

In [52]:
df.dropna(thresh=2) ## Removerá NAN maior ou igual a 2

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [53]:
df.fillna(value='FILL VALUE') ## Preenche os valores de NAN com essa string

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [54]:
data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
'Sales': [200, 120, 340,124,243,350]}

In [55]:
df = pd.DataFrame(data)

In [56]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [57]:
byComp =  df.groupby('Company')

In [58]:
byComp.mean(numeric_only=True) ## Retorna a média

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [59]:
byComp.sum().loc['FB']## Retorna a soma da linha FB

Person    CarlSarah
Sales           593
Name: FB, dtype: object

In [60]:
df.groupby('Company').describe() ## Retorna estatisticas da tabela

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [61]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3']},
                   index=[0, 1, 2, 3])

In [62]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                   'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']},
                   index=[4, 5, 6, 7])

In [63]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                   'B':['B8','B9','B10','B11'],
                   'C':['C8','C9','C10','C11'],
                   'D':['D8','D9','D10','D11']},
                   index=[8,9,10,11])

In [64]:
pd.concat([df1,df2,df3]) ##Concatenação entre os dataFrames criados

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [65]:
left = pd.DataFrame({'Key1':['K0','K0','K1','K2'],
                     'Key2':['K0','K1','K0','K1'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']})

In [68]:
left

  Key1 Key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [66]:
right = pd.DataFrame({'Key1':['K0','K1','K1','K2'],
                     'Key2':['K0','K0','K0','K0'],
                     'C':['C0','C1','C2','C3'],
                     'D':['D0','D1','D2','D3']})

In [69]:
right

  Key1 Key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [67]:
pd.merge(left, right, how='right', on=['Key1','Key2'])

  Key1 Key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [77]:
left.join(right,lsuffix='_left', rsuffix='_right') ##Juncão das duas tabelas

  Key1_left Key2_left   A   B Key1_right Key2_right   C   D
0        K0        K0  A0  B0         K0         K0  C0  D0
1        K0        K1  A1  B1         K1         K0  C1  D1
2        K1        K0  A2  B2         K1         K0  C2  D2
3        K2        K1  A3  B3         K2         K0  C3  D3

In [78]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3': ['abc','def','ghi','xyz']})

In [79]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [81]:
df['col2'].unique() ## retorna os números unicos da col2

array([444, 555, 666])

In [82]:
df['col2'].nunique() ## retorna o número de valores unicos

3

In [83]:
df[(df['col1']>2)&(df['col2']==444)]

   col1  col2 col3
3     4   444  xyz

In [84]:
def times2(x):
    return x*2

In [87]:
df['col1'].apply(times2) ##Vamos aplicar essa funcao que retorna o valor multiplicado por 2

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [90]:
df['col2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [91]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [92]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [94]:
df.sort_values('col2') ##Vai organizar

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [95]:
df.isnull() ##Verifica se existe null

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [97]:
##Data input and output

In [101]:
pd.read_csv('examples/example.csv') ## Ler arquivos CSV

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25280,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25281,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25282,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25283,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25284,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN

In [102]:
df = pd.read_csv('examples/example.csv')

In [103]:
df.to_csv('My_output')

In [106]:
pd.read_csv('My_output') ## Podemos importar um arquivo excel tbm

,Unnamed: 0,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25280,25280,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25281,25281,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25282,25282,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25283,25283,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25284,25284,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN

In [95]:
data = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list') ##Vai pegar todos os dados que estejam dentro de tabelas

In [96]:
data[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

In [97]:
from sqlalchemy import create_engine

In [98]:
engine = create_engine('sqlite:///:memory')

In [99]:
## df.to_sql('my_table') ler dados sql