In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
##Introduction

In [7]:
obj = pd.Series([4,7,-5,3]) ##dimenciona um array com uma dimensão

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [11]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [12]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
obj2 = pd.Series([4, 7, -5, 3], index=["d","b","a","c"]) ##Podemos incluir index custom para o nosso objeto

In [14]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [18]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [20]:
obj2["a"]

np.int64(-5)

In [22]:
obj2["c"] = 6

In [23]:
obj2

d    4
b    7
a   -5
c    6
dtype: int64

In [26]:
obj2[obj2>0] ## Filtragen que vai filtrar um objeto maior do que 0

d    4
b    7
c    6
dtype: int64

In [27]:
obj2*2

d     8
b    14
a   -10
c    12
dtype: int64

In [29]:
np.exp(obj2) ##Podemos utilizar a biblioteca nupy para trabalhar com o pandas

d      54.598150
b    1096.633158
a       0.006738
c     403.428793
dtype: float64

In [30]:
"b" in obj2

True

In [31]:
"f" in obj2

False

In [34]:
sdata = {"Ohio":35000,"Texas":71000,"Oregon":16000, "Utah": 5000} ## Podemos criar um pandas object através de um dictionary

In [33]:
obj3 = pd.Series(sdata)

In [35]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
obj3.to_dict() ##Podemos converter de volta para o dicionario

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [37]:
states = ["California","Ohio","Oregon","Texas"]

In [39]:
obj4 = pd.Series(sdata, index=states)

In [40]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [43]:
pd.isna(obj4) ## isna retorna boolean para dados que estiverem faltando

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [44]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [53]:
## DATAFRAMES, representa uma tabela retangular de dados e contem uma ordem,

In [85]:
##Ele é 2d, ao contrário do Series que é 1d

In [86]:
data = {
    "state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada",],
    "year":[2000, 2001, 2002, 2001, 2002, 2003],
    "pop":[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

In [87]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [88]:
frame = pd.DataFrame(data)

In [89]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [90]:
frame.head() ##Vai demonstrar apenas os primeiros cinco resultados da tabela

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [91]:
frame.tail()## Retorna os ultimos 5 resultados

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [92]:
pd.DataFrame(data, columns=["year","state","pop"]) ## podemos organizar as colunas passando esses parâmetros

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [93]:
frame2 = pd.DataFrame(data, columns=["year","state","pop","debt"])

In [94]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [95]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [96]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [97]:
frame2.loc[1] ## Retorna a primeira linha

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [98]:
frame.iloc[2] ## Retorna a segunda linha

state    Ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [99]:
frame2["debt"] = 16.5 ## Vai destinar a coluna com esses valores

In [100]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [101]:
frame2["debt"] = np.arange(6.) ##sorteia seis na coluna debt

In [102]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0