In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']
my_data = [10, 20, 30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [4]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan']) ##O primeiro seria o index e o segundo os valores

In [7]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [8]:
ser1['USA']

np.int64(1)

In [9]:
ser2 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])## Se existir uma correspondencia entre os index ele somará se não, null

In [10]:
ser2+ser1

USA        2
Germany    4
USSR       6
Japan      8
dtype: int64

In [11]:
##DataFrames

In [12]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [13]:
df

          W         X         Y         Z
A -1.306058  1.038299  1.012560  0.566470
B  0.458838 -1.117526  0.616849  0.160124
C -0.170085  0.560441  0.246342 -1.648360
D -0.996160  1.960422  0.260944 -0.324359
E  1.165622 -0.660569  1.989671  0.552567

In [14]:
df['W'] ##Vai pegar a coluna de w

A   -1.306058
B    0.458838
C   -0.170085
D   -0.996160
E    1.165622
Name: W, dtype: float64

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.W ##Mesma coisa que df['W']

A   -1.306058
B    0.458838
C   -0.170085
D   -0.996160
E    1.165622
Name: W, dtype: float64

In [17]:
df['new'] = df['W'] + df['Y'] ## Criacao de uma nova coluna com o somatório das duas anteriores

In [18]:
df

          W         X         Y         Z       new
A -1.306058  1.038299  1.012560  0.566470 -0.293498
B  0.458838 -1.117526  0.616849  0.160124  1.075687
C -0.170085  0.560441  0.246342 -1.648360  0.076257
D -0.996160  1.960422  0.260944 -0.324359 -0.735216
E  1.165622 -0.660569  1.989671  0.552567  3.155293

In [19]:
df.drop('new',axis=1, inplace=True)## apagar a coluna da tabela, nesse caso precisamos passar o axis = 1 e o nome,e o inplace é a confirmacao que devemos apagar

In [20]:
df[['Z','X']]

          Z         X
A  0.566470  1.038299
B  0.160124 -1.117526
C -1.648360  0.560441
D -0.324359  1.960422
E  0.552567 -0.660569

In [21]:
df.loc['C'] ## Pegar a linha A como referência

W   -0.170085
X    0.560441
Y    0.246342
Z   -1.648360
Name: C, dtype: float64

In [22]:
df.iloc[2] ##iloc passa o indice da linha

W   -0.170085
X    0.560441
Y    0.246342
Z   -1.648360
Name: C, dtype: float64

In [23]:
df.loc['B','Y'] ## O primeiro parâmetro indica a linha e a segunda a coluna

np.float64(0.6168492116382891)

In [24]:
df.loc[['A', 'B'], ['W', 'Y']]

          W         Y
A -1.306058  1.012560
B  0.458838  0.616849

In [25]:
booldf = df>0

In [26]:
booldf

       W      X     Y      Z
A  False   True  True   True
B   True  False  True   True
C  False   True  True  False
D  False   True  True  False
E   True  False  True   True

In [27]:
df[booldf]

          W         X         Y         Z
A       NaN  1.038299  1.012560  0.566470
B  0.458838       NaN  0.616849  0.160124
C       NaN  0.560441  0.246342       NaN
D       NaN  1.960422  0.260944       NaN
E  1.165622       NaN  1.989671  0.552567

In [28]:
df['W'] > 0

A    False
B     True
C    False
D    False
E     True
Name: W, dtype: bool

In [29]:
resultdf = df[df['W']>0]["W"] ##Retornará os valores e não o boolean

In [30]:
resultdf

B    0.458838
E    1.165622
Name: W, dtype: float64

In [31]:
boolser = df["W"]>0 ## Pandas compara cada valor na coluna w com 0
result = df[boolser] ## Usamos essa máscara para filtrar as linhas, e retornar valores
mycols = ['Y','X']##
result[mycols]

          Y         X
B  0.616849 -1.117526
E  1.989671 -0.660569

In [32]:
df

          W         X         Y         Z
A -1.306058  1.038299  1.012560  0.566470
B  0.458838 -1.117526  0.616849  0.160124
C -0.170085  0.560441  0.246342 -1.648360
D -0.996160  1.960422  0.260944 -0.324359
E  1.165622 -0.660569  1.989671  0.552567

In [33]:
df[(df['W']> 0) | (df['Y']> 1)]

          W         X         Y         Z
A -1.306058  1.038299  1.012560  0.566470
B  0.458838 -1.117526  0.616849  0.160124
E  1.165622 -0.660569  1.989671  0.552567

In [34]:
df

          W         X         Y         Z
A -1.306058  1.038299  1.012560  0.566470
B  0.458838 -1.117526  0.616849  0.160124
C -0.170085  0.560441  0.246342 -1.648360
D -0.996160  1.960422  0.260944 -0.324359
E  1.165622 -0.660569  1.989671  0.552567

In [35]:
newind = 'CA NY WY OR CO'.split() ## Criacao de um novo index

In [36]:
df['States'] = newind

In [37]:
df

          W         X         Y         Z States
A -1.306058  1.038299  1.012560  0.566470     CA
B  0.458838 -1.117526  0.616849  0.160124     NY
C -0.170085  0.560441  0.246342 -1.648360     WY
D -0.996160  1.960422  0.260944 -0.324359     OR
E  1.165622 -0.660569  1.989671  0.552567     CO

In [38]:
df.set_index('States') ## Criacao de estados no index

               W         X         Y         Z
States
CA     -1.306058  1.038299  1.012560  0.566470
NY      0.458838 -1.117526  0.616849  0.160124
WY     -0.170085  0.560441  0.246342 -1.648360
OR     -0.996160  1.960422  0.260944 -0.324359
CO      1.165622 -0.660569  1.989671  0.552567

In [39]:
outside = [ 'G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [40]:
df = pd.DataFrame(np.random.randn(6,2),hier_index,['A', 'B'])

In [41]:
df

             A         B
G1 1  0.283900 -0.750792
   2 -0.251129  0.665906
   3 -1.606690  0.666914
G2 1  0.163994  0.149404
   2 -0.129984 -0.893164
   3  1.628602  1.474813

In [42]:
df.index.names = ['Groups','Num']

In [43]:
df

                   A         B
Groups Num
G1     1    0.283900 -0.750792
       2   -0.251129  0.665906
       3   -1.606690  0.666914
G2     1    0.163994  0.149404
       2   -0.129984 -0.893164
       3    1.628602  1.474813

In [44]:
df.loc['G2'].loc[2]

A   -0.129984
B   -0.893164
Name: 2, dtype: float64

In [45]:
df.loc['G1'].loc[1]['B']

np.float64(-0.7507916069025413)

In [46]:
df.xs(1, level="Num")

               A         B
Groups
G1      0.283900 -0.750792
G2      0.163994  0.149404

In [47]:
d = {'A': [1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [48]:
df = pd.DataFrame(d)

In [49]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [50]:
df.dropna() ## Vai dropar todos os valores com NAN

     A    B  C
0  1.0  5.0  1

In [51]:
df.dropna(thresh=2) ## Removerá NAN maior ou igual a 2

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [52]:
df.fillna(value='FILL VALUE') ## Preenche os valores de NAN com essa string

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [53]:
data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
'Sales': [200, 120, 340,124,243,350]}

In [54]:
df = pd.DataFrame(data)

In [55]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [56]:
byComp =  df.groupby('Company')

In [57]:
byComp.mean(numeric_only=True) ## Retorna a média

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [58]:
byComp.sum().loc['FB']## Retorna a soma da linha FB

Person    CarlSarah
Sales           593
Name: FB, dtype: object

In [59]:
df.groupby('Company').describe() ## Retorna estatisticas da tabela

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [60]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3']},
                   index=[0, 1, 2, 3])

In [61]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                   'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],
                   'D':['D4','D5','D6','D7']},
                   index=[4, 5, 6, 7])

In [62]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                   'B':['B8','B9','B10','B11'],
                   'C':['C8','C9','C10','C11'],
                   'D':['D8','D9','D10','D11']},
                   index=[8,9,10,11])

In [63]:
pd.concat([df1,df2,df3]) ##Concatenação entre os dataFrames criados

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [64]:
left = pd.DataFrame({'Key1':['K0','K0','K1','K2'],
                     'Key2':['K0','K1','K0','K1'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']})

In [65]:
left

  Key1 Key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [66]:
right = pd.DataFrame({'Key1':['K0','K1','K1','K2'],
                     'Key2':['K0','K0','K0','K0'],
                     'C':['C0','C1','C2','C3'],
                     'D':['D0','D1','D2','D3']})

In [67]:
right

  Key1 Key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [68]:
pd.merge(left, right, how='right', on=['Key1','Key2'])

  Key1 Key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [69]:
left.join(right,lsuffix='_left', rsuffix='_right') ##Juncão das duas tabelas

  Key1_left Key2_left   A   B Key1_right Key2_right   C   D
0        K0        K0  A0  B0         K0         K0  C0  D0
1        K0        K1  A1  B1         K1         K0  C1  D1
2        K1        K0  A2  B2         K1         K0  C2  D2
3        K2        K1  A3  B3         K2         K0  C3  D3

In [70]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3': ['abc','def','ghi','xyz']})

In [71]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [72]:
df['col2'].unique() ## retorna os números unicos da col2

array([444, 555, 666])

In [73]:
df['col2'].nunique() ## retorna o número de valores unicos

3

In [74]:
df[(df['col1']>2)&(df['col2']==444)]

   col1  col2 col3
3     4   444  xyz

In [75]:
def times2(x):
    return x*2

In [76]:
df['col1'].apply(times2) ##Vamos aplicar essa funcao que retorna o valor multiplicado por 2

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [77]:
df['col2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [78]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [79]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [80]:
df.sort_values('col2') ##Vai organizar

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [81]:
df.isnull() ##Verifica se existe null

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [82]:
##Data input and output

In [83]:
pd.read_csv('examples/example.csv') ## Ler arquivos CSV

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25280,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25281,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25282,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25283,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25284,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN

In [84]:
df = pd.read_csv('examples/example.csv')

In [85]:
df.to_csv('My_output')

In [86]:
pd.read_csv('My_output') ## Podemos importar um arquivo excel tbm

,Unnamed: 0,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25280,25280,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25281,25281,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25282,25282,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25283,25283,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
25284,25284,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN

In [87]:
data = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list') ##Vai pegar todos os dados que estejam dentro de tabelas

In [88]:
data[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [89]:
from sqlalchemy import create_engine

In [90]:
engine = create_engine('sqlite:///:memory')

In [91]:
## df.to_sql('my_table') ler dados sql

In [92]:
obj = pd.Series([4,7,-5,3])

In [93]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [94]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [95]:
obj = pd.Series([4,7,-5,3],index=["d","b","a","c"]) ##Array de series com index customizável

In [96]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [97]:
obj["d"] ##Vai selecionar o index citado

np.int64(4)

In [98]:
obj[obj>0] ## verifica se existe um obj maior do que 2

d    4
b    7
c    3
dtype: int64

In [99]:
obj * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [100]:
np.absolute(obj)

d    4
b    7
a    5
c    3
dtype: int64

In [101]:
"b" in obj ## Verifica se existe algum objeto com essa chave

True

In [102]:
##Tambem podemos criar uma serie através de um dictionary
sdata = {"Ohio":35000,"Texas":71000,"Oregon":16000,"Utah":5000}
obj3 = pd.Series(sdata) ## Transformacao de um obj para serie
obj3.to_dict() ## Tranformação de series para dicionário

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [103]:
##A diferenca entre a Serie e o Dataframe é que o dataframe possui mais de uma coluna
data = {
        "state": ["Ohio", "Ohio", "Ohio","Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5,1.7,3.6,2.4,2.9,3.2]
       }
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [104]:
frame.head()##seleciona os cinco primeiros

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [105]:
frame.tail() ##Retorna os cinco ultimos

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [106]:
pd.DataFrame(data, columns=["year","state","pop"]) ##Podemos mudar a ordem das colunas

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [107]:
frame["year"] ## ou podemos seguir com a seguinte notação frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [108]:
frame.iloc[2] ## vai pegar a linha 2 da tabela

state    Ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [109]:
frame["debt"] = 16.5 ## nova coluna será adicionada com esse valor

In [110]:
frame["debt"] = np.arange(6.)

In [111]:
frame

    state  year  pop  debt
0    Ohio  2000  1.5   0.0
1    Ohio  2001  1.7   1.0
2    Ohio  2002  3.6   2.0
3  Nevada  2001  2.4   3.0
4  Nevada  2002  2.9   4.0
5  Nevada  2003  3.2   5.0

In [112]:
del frame["debt"] ## Vamos deletar o "debt"

In [113]:
populations = {"Ohio":{2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada":{2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [114]:
frame3.T ## Vamos trocar a coluna pela linha e vice versa

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [119]:
obj = pd.Series(np.arange(3), index=["a","b","c"])
index = obj.index
obj

a    0
b    1
c    2
dtype: int64

In [117]:
obj.index.name = "year"

In [121]:
index[1:]

Index(['b', 'c'], dtype='object')

In [122]:
obj2 = pd.Series([1.5, -2.5, 0],index=labels)

In [123]:
obj2

a    1.5
b   -2.5
c    0.0
dtype: float64

In [126]:
pd.Index(["foo","foo","bar","bar"]) ## No Index é permitido colocar duas labels repetidas

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [136]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj2 = obj.reindex(["a","b","c","d","e"]) ## O reindex introduz novas informacões
obj2["e"] = 7.2
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    7.2
dtype: float64

In [142]:
obj3 = pd.Series(["blue", "purple","yellow"],index=[0, 2, 4])
obj3.reindex(np.arange(6), method="ffill") ## O método ffill preencherá todos os elementos que forem NAN

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [145]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), 
                     index=["a","c","d"],
                     columns=["Ohio","Texas","California"])
## Nesse caso aqui ele formará um quadro com dados sortidos de 0 até 9 com um shape de 3,3 e com coluna de cidade e index de letras
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [147]:
frame2 = frame.reindex(index=["a","b","c","d"],columns=["Texas","Utah","California"])
frame2

   Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [148]:
frame.loc[["a","d","c"],["California","Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

In [151]:
frame2.drop(index="c") ## Vai retirar a linha "c"

   Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
d    7.0   NaN         8.0

In [153]:
frame2.drop(columns=["Utah"]) ## Vai retirar a coluna "Utah"

   Texas  California
a    1.0         2.0
b    NaN         NaN
c    4.0         5.0
d    7.0         8.0

In [156]:
obj = pd.Series(np.arange(4.),index=["a","b","c","d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [157]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [160]:
obj.loc[["b","a","d"]] ##localização de forma mais recomendada "df.loc[linhas, colunas]", é mais proficional

b    1.0
a    0.0
d    3.0
dtype: float64

In [174]:
obj.iloc[[0, 1]] ##usa-se posicao numérica, por indice

a    0.0
b    1.0
dtype: float64

In [175]:
obj.iloc[[0]]

a    0.0
dtype: float64

In [176]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio","Colorado","Utah","New York"],
                    columns=["one","two","three","four"])

In [177]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [178]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [181]:
data[data["three"]>5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [187]:
data.loc["Colorado",["two"]]

two    5
Name: Colorado, dtype: int64

In [190]:
data.loc[["Colorado"],["two"]]

          two
Colorado    5

In [191]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [195]:
data.iloc[[2,1]] ## Vai printar o indice das linhas 2 e 1

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [200]:
data.loc[:"Utah","two"]

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64